"""Certificate PDF generation helpers."""

from io import BytesIO


_FALLBACK_PDF = b"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 106 >>
stream
BT
/F1 16 Tf
72 740 Td
(Certificate) Tj
0 -24 Td
/F1 12 Tf
(Generated by MediaCMS LMS.) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f
0000000010 00000 n
0000000062 00000 n
0000000120 00000 n
0000000248 00000 n
0000000405 00000 n
trailer
<< /Size 6 /Root 1 0 R >>
startxref
491
%%EOF
"""


def _generate_with_reportlab(context: dict) -> bytes:
    def _safe_font(name: str, size: int):
        try:
            c.setFont(name, size)
        except Exception:
            c.setFont("Helvetica", size)

    def _draw_centered_fit(text: str, x: float, y: float, font_name: str, start_size: int, max_width: float):
        size = start_size
        clean = str(text or "")
        while size > 10:
            _safe_font(font_name, size)
            if c.stringWidth(clean, c._fontname, size) <= max_width:
                break
            size -= 1
        c.drawCentredString(x, y, clean)

    from reportlab.lib.pagesizes import LETTER, landscape, portrait
    from reportlab.pdfgen import canvas

    page = landscape(LETTER) if context.get("orientation") == "landscape" else portrait(LETTER)
    width, height = page
    buff = BytesIO()
    c = canvas.Canvas(buff, pagesize=page)
    c.setTitle("Course Certificate")
    bg_path = context.get("background_image_path")
    if bg_path:
        try:
            c.drawImage(bg_path, 0, 0, width=width, height=height, preserveAspectRatio=False, mask="auto")
        except Exception:
            pass

    layout = context.get("layout") or {}
    title_x = float(layout.get("title_x", width / 2))
    title_y = float(layout.get("title_y", height - 92))
    recipient_x = float(layout.get("recipient_x", width / 2))
    recipient_y = float(layout.get("recipient_y", height - 160))
    course_x = float(layout.get("course_x", width / 2))
    course_y = float(layout.get("course_y", height - 225))
    verify_x = float(layout.get("verify_x", width / 2))
    verify_y = float(layout.get("verify_y", height - 270))
    line_gap = float(layout.get("line_gap", 24))
    title_size = int(layout.get("title_font_size", 24))
    recipient_size = int(layout.get("recipient_font_size", 26))
    course_size = int(layout.get("course_font_size", 16))
    verify_size = int(layout.get("verify_font_size", 10))
    font_name = context.get("font_family") or "Helvetica"

    title_font = f"{font_name}-Bold" if font_name != "Helvetica" else "Helvetica-Bold"
    _safe_font(title_font, title_size)
    c.drawCentredString(title_x, title_y, "Certificate of Completion")
    _safe_font(font_name, max(10, recipient_size // 2))
    _draw_centered_fit(context["recipient"], recipient_x, recipient_y, title_font, recipient_size, width * 0.8)
    c.drawCentredString(recipient_x, recipient_y - line_gap, "has successfully completed")
    _draw_centered_fit(context["course_title"], course_x, course_y, title_font, course_size, width * 0.85)
    _safe_font(font_name, verify_size)
    c.drawCentredString(verify_x, verify_y, f"Verification code: {context['verification_code']}")
    c.drawCentredString(verify_x, verify_y - max(12, verify_size + 2), f"Issued: {context['issued_at']}")

    sig_path = context.get("signature_path")
    if sig_path:
        sig_x = float(layout.get("signature_x", width * 0.65))
        sig_y = float(layout.get("signature_y", 48))
        sig_w = float(layout.get("signature_w", 160))
        sig_h = float(layout.get("signature_h", 60))
        try:
            c.drawImage(sig_path, sig_x, sig_y, width=sig_w, height=sig_h, preserveAspectRatio=True, mask="auto")
        except Exception:
            pass
    c.showPage()
    c.save()
    return buff.getvalue()


def generate_certificate_pdf_bytes(context: dict, generator: str = "reportlab") -> bytes:
    """Return PDF bytes for the given certificate context."""
    if generator == "reportlab":
        try:
            return _generate_with_reportlab(context)
        except Exception:
            return _FALLBACK_PDF
    return _FALLBACK_PDF
